# Generated by Django 4.2.5 on 2023-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('autor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('dra', 'черновик'), ('act', 'опубликовано')], default='dra', max_length=3)),
            ],
        ),
    ]
